name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    paths:
      - 'be/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'be/**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual trigger'

jobs:
  build:

    env:
      MYSQL_IP: ${{secrets.MYSQL_IP}}
      MYSQL_DB_NAME: ${{secrets.MYSQL_DB_NAME}}
      MYSQL_USERNAME: ${{secrets.MYSQL_USERNAME}}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: |
        cd be
        ./gradlew build
